---
kind: Service
apiVersion: v1
metadata:
  {{- if .Values.prefix }}
  name: {{ .Values.prefix }}-{{ .Chart.Name }}-public-svc
  labels:
    app: {{ .Values.prefix }}-{{ .Chart.Name }}
  {{- else }}
  name: {{ .Chart.Name }}-public-svc
  labels:
    app: {{ .Chart.Name }}
  {{- end }}
spec:
  type: {{ .Values.service.public.type }}
  ports:
    {{- range .Values.service.public.ports }}
      - name: {{ .name }}
        port: {{ .port }}
        targetPort: {{ .targetPort }}
        nodePort: {{ .nodePort }}
    {{- end }}
  selector:
    {{- if .Values.prefix }}
    app: {{ .Values.prefix }}-{{ .Chart.Name }}
    {{- else }}
    app: {{ .Chart.Name }}
    {{- end }}
