apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service-viewer-2
  name: frontend-service-viewer-2-svc
  namespace: default
spec:
  ports:
  - name: application
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: frontend-service-viewer-2
  sessionAffinity: None
  type: ClusterIP
